#!/usr/bin/env bash
# ----------------------------------------------------------------------------
# extras/security-onion-config-backup.sh
# ----------------------------------------------------------------------------
# Lightweight Security Onion config backup — captures only what is needed
# to rebuild or restore a SO 3.0.x standalone instance after a reinstall.
# Tested on Security Onion 3.0.0 / Oracle Linux 9.7.
#
# What this script collects (~few MB total):
#
#   /opt/so/saltstack/local/pillar/   your actual SO settings (180 KB)
#   /etc/salt/                        Salt master config (112 KB)
#   /etc/yum.repos.d/securityonion.repo
#   _state/ runtime snapshot:
#     so-status output                container health table
#     docker images + ps              all SO container image versions
#     salt pillar dump                effective config (REVIEW FOR SECRETS)
#     uname + os-release              host fingerprint
#
# What this script DOES NOT collect (and why):
#   /opt/so/saltstack/local/salt/     1.3 GB of Salt states generated by SO
#                                     at install time — recreated on reinstall
#   /opt/so/saltstack/default/        vendor defaults — same reason
#   /opt/so/conf/                     1.6 GB of container configs generated
#                                     by Salt — same reason
#   /opt/so/rules/suricata/all-rulesets.rules   31 MB, auto-updated by SO
#   Custom Suricata rules             none on a fresh install; add the path
#                                     below if you create local.rules later
#
# Must be run as root (sudo -i before invoking, or via cron as root).
#
# Schedule: weekly is plenty.
#   30 04 * * 0 /usr/local/sbin/security-onion-config-backup.sh
#
# License: MIT — see LICENSE in the repository root.
# ----------------------------------------------------------------------------

set -Eeuo pipefail
umask 077

DEST_DIR="${SO_BACKUP_DIR:-/var/backups/securityonion}"
RETENTION_COUNT="${SO_BACKUP_RETENTION:-12}"
LOG_FILE="${LOG_FILE:-/var/log/security-onion-config-backup.log}"

ALERT_TO="${ALERT_TO:-admin@example.org}"
ALERT_FROM="${ALERT_FROM:-root@$(hostname -f 2>/dev/null || hostname)}"
ALERT_SMTP_SERVER="${ALERT_SMTP_SERVER:-web-mail.example.org}"
ALERT_SMTP_PORT="${ALERT_SMTP_PORT:-465}"
ALERT_SMTP_USER="${ALERT_SMTP_USER:-admin@example.org}"
ALERT_SMTP_PASSWORD_FILE="${ALERT_SMTP_PASSWORD_FILE:-/root/backup-orchestrator/.smtp_pass}"

# ---- Paths to capture ----
# Add /opt/so/rules/suricata/local.rules here once you create custom rules.
PATHS_TO_CAPTURE=(
  "/opt/so/saltstack/local/pillar"
  "/etc/salt"
  "/etc/yum.repos.d/securityonion.repo"
  "/opt/so/rules/suricata/local.rules"
)

# ---- Detect SO version ----
SO_VERSION="$(cat /etc/soversion 2>/dev/null || echo unknown)"

# ---- Setup ----
mkdir -p "$DEST_DIR" "$(dirname "$LOG_FILE")"
exec > >(tee -a "$LOG_FILE") 2>&1

ts="$(date +%Y%m%d-%H%M%S)"
work_dir="$(mktemp -d /tmp/so-config-backup.XXXXXX)"
out_file="$DEST_DIR/securityonion-config-${ts}.tar.gz"

cleanup() { rm -rf "$work_dir"; }
trap cleanup EXIT

echo
echo "================================================================"
echo "security-onion-config-backup — $(date)"
echo "  SO version:  ${SO_VERSION:-unknown}"
echo "  OS:          $(grep PRETTY_NAME /etc/os-release | cut -d= -f2 | tr -d '\"')"
echo "  destination: $out_file"
echo "  retention:   $RETENTION_COUNT archives"
echo "================================================================"

# ---- 1. Copy filesystem paths ----
echo
echo "[1/4] Copying configuration paths ..."
for p in "${PATHS_TO_CAPTURE[@]}"; do
  if [ -e "$p" ]; then
    rel_dir="$(dirname "$p")"
    mkdir -p "$work_dir${rel_dir}"
    cp -a "$p" "$work_dir${rel_dir}/" 2>>"$LOG_FILE" \
      && echo "  + $p" \
      || echo "  WARN: cp failed for $p"
  else
    echo "  - $p (skipped, does not exist)"
  fi
done

# ---- 2. Capture runtime state ----
echo
echo "[2/4] Capturing runtime state ..."
state_dir="$work_dir/_state"
mkdir -p "$state_dir"

# Host fingerprint
uname -a > "$state_dir/uname.txt" 2>&1 || true
cp /etc/os-release "$state_dir/os-release.txt" 2>/dev/null || true
echo "$SO_VERSION" > "$state_dir/so-version.txt"
echo "  + host fingerprint"

# Container health table
if command -v so-status >/dev/null 2>&1; then
  so-status > "$state_dir/so-status.txt" 2>&1 || true
  echo "  + so-status"
fi

# Docker image versions (SO 3.0 runs everything in Docker)
if command -v docker >/dev/null 2>&1; then
  docker images > "$state_dir/docker-images.txt" 2>&1 || true
  docker ps -a  > "$state_dir/docker-ps.txt"     2>&1 || true
  echo "  + docker images + ps ($(docker ps -q 2>/dev/null | wc -l) containers running)"
fi

# Salt pillar dump — the effective config values as Salt sees them.
# IMPORTANT: may contain passwords and internal addresses.
# Review before transferring or sharing this archive.
if command -v salt-call >/dev/null 2>&1; then
  salt-call --local pillar.items > "$state_dir/pillar.items.txt" 2>&1 || true
  echo "  + pillar.items  *** REVIEW FOR SECRETS BEFORE EXPORTING ***"
fi

# ---- 3. Compress and rotate ----
echo
echo "[3/4] Building archive ..."
tar -C "$work_dir" -cz -f "$out_file" .
chmod 0600 "$out_file"

size="$(du -h "$out_file" | awk '{print $1}')"
echo "  archive: $out_file ($size)"

ls -t "$DEST_DIR"/securityonion-config-*.tar.gz 2>/dev/null \
  | tail -n +$((RETENTION_COUNT + 1)) | xargs -r rm --

# ---- 4. Summary ----
echo
echo "================================================================"
echo "DONE — $size archive ready for offsite transfer"
echo "================================================================"

# ---- Optional: ship via the LUKS chain (uncomment and adjust) ----
# . /root/backup-orchestrator/luks_functions.sh
# prepare_luks_mount "ssh -q nas-core 'cat /volume1/NetBackup/.ash'" \
#   /home/Backup_SecOnion.crypt Backup_SecOnion_crypt /home/tmp_crypt
# scp -P 1622 "$out_file" root@mx-secondary.example.org:/home/tmp_crypt/
# close_luks_mount Backup_SecOnion_crypt /home/tmp_crypt

exit 0